jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Allow PowerShell script execution
      shell: powershell
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope Process -Force

    - name: Set up Docker to use Minikube's environment
      shell: powershell
      run: |
        & minikube -p minikube docker-env --shell=powershell | Invoke-Expression

    - name: Build frontend Docker image
      run: docker build -t haseebsajid/frontend:latest ./frontend

    - name: Build backend Docker image
      run: docker build -t haseebsajid/backend:latest ./backend

    - name: Push images to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push haseebsajid/frontend:latest
        docker push haseebsajid/backend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/backend-deployment.yml
        kubectl apply -f k8s/backend-service.yml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yml
